# Generated by Django 6.0.2 on 2026-02-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('brute_force', 'Brute Force Attempt'), ('rate_limit', 'Rate Limit Exceeded'), ('honeypot', 'Honeypot Triggered'), ('suspicious', 'Suspicious Activity')], max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('source_ip', models.GenericIPAddressField()),
                ('target', models.CharField(max_length=255)),
                ('endpoint', models.CharField(max_length=255)),
                ('attempts', models.IntegerField(default=1)),
                ('user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('blocked', 'Blocked'), ('limited', 'Rate Limited'), ('monitoring', 'Under Monitoring'), ('resolved', 'Resolved')], max_length=20)),
                ('action_taken', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('country', models.CharField(blank=True, max_length=100)),
                ('isp', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('error_type', models.CharField(choices=[('database', 'Database Error'), ('api', 'API Error'), ('network', 'Network Issue'), ('security', 'Security Alert'), ('application', 'Application Error'), ('cache', 'Cache Error')], max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('source', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('blocked', 'Blocked'), ('limited', 'Rate Limited'), ('monitoring', 'Under Monitoring'), ('resolved', 'Resolved')], max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField()),
                ('cpu_temperature', models.FloatField(blank=True, null=True)),
                ('memory_used', models.FloatField()),
                ('memory_total', models.FloatField()),
                ('disk_used', models.FloatField()),
                ('disk_total', models.FloatField()),
                ('network_incoming', models.FloatField()),
                ('network_outgoing', models.FloatField()),
                ('active_connections', models.IntegerField()),
                ('database_connections', models.IntegerField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
