# Generated by Django 6.0.2 on 2026-02-26 12:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('local', 'Local Storage'), ('s3', 'AWS S3'), ('gcs', 'Google Cloud Storage'), ('azure', 'Azure Blob Storage'), ('both', 'Local + Cloud'), ('cold', 'Cold Storage')], max_length=20)),
                ('host', models.CharField(blank=True, max_length=500)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('password_encrypted', models.CharField(blank=True, max_length=500)),
                ('bucket_name', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('access_key', models.CharField(blank=True, max_length=500)),
                ('secret_key_encrypted', models.CharField(blank=True, max_length=500)),
                ('base_path', models.CharField(max_length=1000)),
                ('total_space_gb', models.FloatField(blank=True, null=True)),
                ('used_space_gb', models.FloatField(default=0)),
                ('free_space_gb', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('maintenance', 'Maintenance')], default='active', max_length=20)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackupStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_backups', models.PositiveIntegerField(default=0)),
                ('successful_backups', models.PositiveIntegerField(default=0)),
                ('failed_backups', models.PositiveIntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(default=0)),
                ('total_size_gb', models.FloatField(default=0)),
                ('average_size_bytes', models.BigIntegerField(default=0)),
                ('full_backups', models.PositiveIntegerField(default=0)),
                ('incremental_backups', models.PositiveIntegerField(default=0)),
                ('transaction_logs', models.PositiveIntegerField(default=0)),
                ('local_storage_gb', models.FloatField(default=0)),
                ('cloud_storage_gb', models.FloatField(default=0)),
                ('cold_storage_gb', models.FloatField(default=0)),
                ('total_duration_seconds', models.PositiveIntegerField(default=0)),
                ('average_duration_seconds', models.FloatField(default=0)),
                ('active_schedules', models.PositiveIntegerField(default=0)),
                ('paused_schedules', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Backup statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('backup_type', models.CharField(choices=[('full', 'Full Backup'), ('incremental', 'Incremental'), ('transaction_log', 'Transaction Log'), ('differential', 'Differential')], default='full', max_length=20)),
                ('frequency', models.CharField(choices=[('continuous', 'Continuous (Every 15 min)'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom Cron')], default='daily', max_length=20)),
                ('cron_expression', models.CharField(blank=True, help_text="Custom cron for 'custom' frequency", max_length=100)),
                ('scheduled_time', models.TimeField(blank=True, help_text='For daily/weekly schedules', null=True)),
                ('scheduled_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of week (0-6) or month (1-31)', null=True)),
                ('retention_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('retention_count', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('destination_type', models.CharField(choices=[('local', 'Local Storage'), ('s3', 'AWS S3'), ('gcs', 'Google Cloud Storage'), ('azure', 'Azure Blob Storage'), ('both', 'Local + Cloud'), ('cold', 'Cold Storage')], default='local', max_length=20)),
                ('destination_path', models.CharField(blank=True, max_length=500)),
                ('s3_bucket', models.CharField(blank=True, max_length=200)),
                ('s3_path', models.CharField(blank=True, max_length=500)),
                ('compression_enabled', models.BooleanField(default=True)),
                ('encryption_enabled', models.BooleanField(default=True)),
                ('verification_enabled', models.BooleanField(default=True)),
                ('notify_on_success', models.BooleanField(default=True)),
                ('notify_on_failure', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('is_running', models.BooleanField(default=False)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, max_length=20)),
                ('last_run_message', models.TextField(blank=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('successful_runs', models.PositiveIntegerField(default=0)),
                ('failed_runs', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('backup_type', models.CharField(choices=[('full', 'Full Backup'), ('incremental', 'Incremental'), ('transaction_log', 'Transaction Log'), ('differential', 'Differential')], max_length=20)),
                ('filename', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=1000)),
                ('file_size', models.CharField(help_text='Human readable size', max_length=50)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('checksum_type', models.CharField(default='sha256', max_length=20)),
                ('database_name', models.CharField(default='default', max_length=200)),
                ('database_version', models.CharField(blank=True, max_length=50)),
                ('backup_version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('warning', 'Warning'), ('verified', 'Verified'), ('expired', 'Expired'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('verification_status', models.CharField(blank=True, max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('location_type', models.CharField(choices=[('local', 'Local Storage'), ('s3', 'AWS S3'), ('gcs', 'Google Cloud Storage'), ('azure', 'Azure Blob Storage'), ('both', 'Local + Cloud'), ('cold', 'Cold Storage')], default='local', max_length=20)),
                ('location_path', models.CharField(max_length=1000)),
                ('s3_bucket', models.CharField(blank=True, max_length=200)),
                ('s3_key', models.CharField(blank=True, max_length=1000)),
                ('compression_enabled', models.BooleanField(default=True)),
                ('encryption_enabled', models.BooleanField(default=True)),
                ('encryption_algorithm', models.CharField(blank=True, max_length=50)),
                ('log_file', models.CharField(blank=True, max_length=1000)),
                ('error_message', models.TextField(blank=True)),
                ('warning_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='database_backup.backupschedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='database_backup.backupschedule')),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='database_backup.databasebackup')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='backupschedule',
            index=models.Index(fields=['status', 'next_run'], name='database_ba_status_22b031_idx'),
        ),
        migrations.AddIndex(
            model_name='backupschedule',
            index=models.Index(fields=['backup_type'], name='database_ba_backup__dad755_idx'),
        ),
        migrations.AddIndex(
            model_name='databasebackup',
            index=models.Index(fields=['status', 'created_at'], name='database_ba_status_26ec05_idx'),
        ),
        migrations.AddIndex(
            model_name='databasebackup',
            index=models.Index(fields=['backup_type'], name='database_ba_backup__2f90fc_idx'),
        ),
        migrations.AddIndex(
            model_name='databasebackup',
            index=models.Index(fields=['expires_at'], name='database_ba_expires_7b36af_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['backup', 'timestamp'], name='database_ba_backup__b70ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='backuplog',
            index=models.Index(fields=['level'], name='database_ba_level_43f0c2_idx'),
        ),
    ]
