# Generated by Django 6.0.2 on 2026-03-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_backup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupdestination',
            options={'ordering': ['-is_default', 'priority']},
        ),
        migrations.AlterModelOptions(
            name='backuplog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='backupschedule',
            name='scheduled_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of week (0-6 for weekly) or day of month (1-31 for monthly)', null=True),
        ),
        migrations.AlterField(
            model_name='databasebackup',
            name='file_size',
            field=models.CharField(blank=True, help_text='Human readable size', max_length=50),
        ),
    ]
