# Generated by Django 6.0.2 on 2026-03-09 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('focal', '0002_focal_email_focal_phone_number_focal_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='focal',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='focal.focal'),
        ),
    ]
