# Generated by Django 6.0.2 on 2026-02-25 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('ADMIN', 'Admin'), ('CALL_CENTER', 'Call Center'), ('BRANCH_MANAGER', 'Branch Manager')], default='CALL_CENTER', max_length=20),
        ),
    ]
