# Generated by Django 6.0.2 on 2026-03-09 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_remove_complaint_feedback_and_more'),
        ('customer', '0002_customer_focal'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
            preserve_default=False,
        ),
    ]
